ame: Build Release Notes

on:
  push:
    tags: [ "*" ]

jobs:
  build-release:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Hack
        run: |
          echo "github.ref: ${{ github.ref }}"