# A Workflow for triggering a new release.

name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Ensure build is green
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew check
      - name: Fetch all tags
        run: git fetch --tags --unshallow
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
        run: |
          ./gradlew release \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}

