# A Workflow for triggering GitHub's dependabot
#
# The workflow provides a deterministic API / URL for triggering GitHub's dependabot.
# The workflow adjusts the whitespace at the end of the .github/dependabot.yml file.
# Changes to this file trigger dependabot.

name: Trigger dependabot

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger_dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Modify dependabot.yml
        run: |
          # Remove duplicate blank lines in file:
          cat -s .github/dependabot.yml > tmp.yml
          mv -f tmp.yml .github/dependabot.yml
          
          # If this doesn't change the file:
          if [[ $(git ls-files -m) == "" ]]; then
            # Append a blank line:
            echo "" >> .github/dependabot.yml
          fi
      - name: Configure Git
        run: |
          git config --global user.email "95620007+Creek-Bot@users.noreply.github.com"
          git config --global user.name "Creek Bot"
          git status
          git add -A
          git commit -m "Trigger dependabot"
          git push --set-upstream origin "create-trigger-dependabot-${{ github.run_number }}"
      - name: Create pull request
        run: |
          echo "PR created: $(gh pr create --title 'Trigger dependabot' --body 'PR created by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/blob/main/${{ github.event.workflow }}) workflow, run [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).')" >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}