# A Workflow for triggering GitHub's dependabot
#
# The workflow provides a deterministic API / URL for triggering GitHub's dependabot.
# The workflow adjusts the whitespace at the end of the .github/dependabot.yml file.
# Changes to this file trigger dependabot.

name: Trigger dependabot

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger_dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Modify dependabot.yml
        run: |
          cat -s .github/dependabot.yml > tmp.yml
          mv -f tmp.yml .github/dependabot.yml
          if [[ $(git ls-files -m) == "" ]]; then
            echo >> .github/dependabot.yml
          fi
      - name: Configure Git
        run: |
          git config --global user.email "95620007+Creek-Bot@users.noreply.github.com"
          git config --global user.name "Creek Bot"
          git checkout -b "create-trigger-dependabot-${{ github.run_number }}"
          git add -A
          git commit -m "Trigger dependabot"
          git push --set-upstream origin "create-trigger-dependabot-${{ github.run_number }}"
      - name: Create pull request
        run: |
          echo "PR created: $(gh pr create --title 'Trigger dependabot' --body 'PR created by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/blob/main/${{ github.event.workflow }}) workflow, run [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).')" >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}