name: Version

on:
  workflow_dispatch:
    inputs:
      part:
        description: "Part to increment: Major, Minor, Patch, or Release (case-sensitive)"
        required: true
        default: Patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Fetch all tags
        run: git fetch --tags --unshallow
      - name: Bump version
        if: github.event.inputs.part != 'Release'
        run: ./gradlew markNextVersion -Prelease.incrementer=increment${{ github.event.inputs.part }}
      - name: Release
        if: github.event.inputs.part == 'Release'
        run: |
          ./gradlew release \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}
      - name: Raise Docs PR
        if: github.event.inputs.part == 'Release'
        uses: peter-evans/create-pull-request@v4
        id: cpr
      - name: PR Details
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Trigger Build
        run: |
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/gradle.yml/dispatches" -d '{"ref":"main","inputs":{"publish":"true"}}'
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
